@echo off
echo Updating Navigation Menus...
node update_all_menus.js
echo Applying Internal Links...
node add_internal_links.js
echo Pushing to GitHub...
powershell -ExecutionPolicy Bypass -File fix_404_deploy.ps1
pause
